// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoPractico;

namespace TrabajoPractico.Migrations
{
    [DbContext(typeof(TPDBContext))]
    [Migration("20201007215756_Migracion07-10")]
    partial class Migracion0710
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TrabajoPractico.Detalles", b =>
                {
                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("recursonombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("fecha");

                    b.HasIndex("recursonombre");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("TrabajoPractico.Recursos", b =>
                {
                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("nombre");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("TrabajoPractico.Tareas", b =>
                {
                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("String")
                        .HasColumnType("INTEGER");

                    b.Property<int>("estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("responsable")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("titulo");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TrabajoPractico.Usuarios", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.HasKey("Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TrabajoPractico.Detalles", b =>
                {
                    b.HasOne("TrabajoPractico.Recursos", "recurso")
                        .WithMany()
                        .HasForeignKey("recursonombre");
                });
#pragma warning restore 612, 618
        }
    }
}
