// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoPractico;

namespace TrabajoPractico.Migrations
{
    [DbContext(typeof(TPDBContext))]
    [Migration("20201008235000_Test3")]
    partial class Test3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TrabajoPractico.Detalles", b =>
                {
                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecursoNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Fecha");

                    b.HasIndex("RecursoNombre");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("TrabajoPractico.Recursos", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Nombre");

                    b.HasIndex("Usuario1");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("TrabajoPractico.Tareas", b =>
                {
                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Titulo");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TrabajoPractico.Usuarios", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TrabajoPractico.Detalles", b =>
                {
                    b.HasOne("TrabajoPractico.Recursos", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrabajoPractico.Recursos", b =>
                {
                    b.HasOne("TrabajoPractico.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
